spring.application.name=taxi

server.port=3001

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_brousse
spring.datasource.username=postgres
spring.datasource.password=motdepasse
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configuration des vues JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp